### ISSUE TITLE
Neos 7.x compatibility

### ISSUE THREAD

**Issue by paavo** [flownative/neos-cachemanagement#4]

**Comment by kdambekalns** [comment]
Fixed with #5

**Comment by paavo** [comment]
Thanks @kdambekalns 
Will you create a new release?

**Comment by kitsunet** [comment]
Isn't that 2.1.2 ?

**Comment by kdambekalns** [comment]
Yes, it is, according to Git.

**Comment by paavo** [comment]
Oh, looks like i had an old version constraints 🙈 
Thanks and have a nice day 👋
